name: Update DNS List

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate DNS List
        run: |
          # 给予脚本执行权限
          chmod +x address-list
          
          # 直接运行本地脚本，生成临时列表文件
          ./address-list -o /tmp/address-list.txt -l

          # 格式化输出为 .rsc 文件
          echo "# MikroTik RouterOS DNS Forward address-list.rsc" > address-list.rsc
          echo "# Update time: $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S') CST" >> address-list.rsc
          echo "#" >> address-list.rsc
          echo "/ip dns static" >> address-list.rsc
          echo "remove [find forward-to=1.1.1.1]" >> address-list.rsc
          echo "remove [find forward-to=1.1.1.1]" >> address-list.rsc
          echo ":delay 10" >> address-list.rsc
          sed "s/^/add type=FWD match-subdomain=yes forward-to=1.1.1.1 address-list=1.1.1.1 name=&/g" /tmp/address-list.txt >> address-list.rsc

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add address-list.rsc
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update address-list.rsc" && git push)
